### ISSUE TITLE
Change "Playing Jetbrains IDE" into "Playing <Application Name>" instead?

### ISSUE THREAD

**Issue by chiqors** [re-ovo/discord-ij#3]
well the title says it. That would be better for quick read status

**Comment by re-ovo** [comment]
better to add a %ide_name% placeholder

**Comment by chiqors** [comment]
also, fix the names when you hover the icon/small icon on discord.. it's still using coded name, if i am not wrong.. like still using uppercase for languange name and using underscore for like "IDEA_ULTIMATE"

**Comment by re-ovo** [comment]
One fact is that Discord doesn't allow to dynamically change the name of the application, if you want multiple names, you need to register a Discord Application ID for each IDE, which is a waste of time
